//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alojamiento
    {
        public string Rut { get; set; }
        public string NombreMascota { get; set; }
        public int IdTipoMascota { get; set; }
        public int IdTipoAlojamiento { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public int Dias { get; set; }
    
        public virtual TipoAlojamiento TipoAlojamiento { get; set; }
        public virtual TipoMascota TipoMascota { get; set; }
        public virtual Propietario Propietario { get; set; }
    }
}
