//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoMascota
    {
        public TipoMascota()
        {
            this.Alojamiento = new HashSet<Alojamiento>();
        }
    
        public int IdTipoMascota { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Alojamiento> Alojamiento { get; set; }
    }
}
